[dropbox]
app_key       = "x6vmemfoizecjvd"
app_secret    = "lzrdu8n8uq2v2lr"
refresh_token = "TCGyaXo5n7YAAAAAAAAAAQnjnPxOEGkTYqr7B0kmohgO6UCyvTIG_wrc2mtWd5IN"
remote_path   = "/Historico Mayoristas/historico_mayoristas.xlsx"